services:
  thebuoy:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: thefiltershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: totolebo
      POSTGRES_HOST: db   # 👈 THIS is the key
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: thefiltershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: totolebo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: