from .main import index
from .viewAGame import game
from .indexOnlineShop import index_online_shops
from .indexOnlineShop import online_shop
from .listGames import get_artisans_games
from .listGames import get_indies_games
from .showCurators import get_curators
from .getFilters import get_all_filters
from .getFilters import get_all_filters_for_an_entity_type_videogame
from .getFilters import get_one_filter_and_related_filters