# Generated by Django 4.2.1 on 2023-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='in_hall_of_shame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='in_hall_of_shame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studio',
            name='fully_rotten',
            field=models.BooleanField(default=False),
        ),
    ]
