# Generated by Django 4.2.1 on 2023-05-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='child_tags',
        ),
        migrations.RemoveField(
            model_name='videogame_common',
            name='ratings',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filtershop_main.tag'),
        ),
        migrations.AddField(
            model_name='videogame_rating',
            name='Videogame_common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.videogame_common'),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tags',
        ),
        migrations.AlterField(
            model_name='person',
            name='nb_of_articles',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filtershop_main.platform'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(to='filtershop_main.tag'),
        ),
    ]
