# Generated by Django 4.2.1 on 2023-05-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0002_remove_person_type_remove_tag_child_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=4000)),
                ('is_positive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('biography', models.CharField(max_length=3000)),
                ('nb_of_articles', models.IntegerField(default=0, editable=False)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=4000)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('filters', models.ManyToManyField(to='filtershop_main.filter')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=4000)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('filters', models.ManyToManyField(to='filtershop_main.filter')),
            ],
        ),
        migrations.CreateModel(
            name='ValueForFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=50)),
                ('description', models.CharField(max_length=1000)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.filter')),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='cheating_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='cheating_review',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='desc_cheating_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='desc_insulting_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='desc_misleading_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='ethical_educational_rating',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='ethical_marketing_rating',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='ethical_money_rating',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='ethical_moral_rating',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='insulting_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='misleading_ads',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='type',
        ),
        migrations.AlterField(
            model_name='entity',
            name='Links_to_shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='filtershop_main.links_to_shops'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='valueforfilter',
            name='for_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='Entity_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='filtershop_main.entity_category'),
        ),
        migrations.AddField(
            model_name='entity',
            name='for_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='filtershop_main.typeofentity'),
            preserve_default=False,
        ),
    ]
