# Generated by Django 4.2.1 on 2023-06-25 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0002_alter_entity_in_hall_of_shame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Shop',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filtershop_main.entity')),
                ('shop_type', models.CharField(max_length=300)),
                ('ethical_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('clarity_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('spotlight_count', models.IntegerField(default=0)),
                ('they_have_made_it', models.IntegerField()),
                ('shop_logo', models.ImageField(upload_to='')),
                ('group', models.ManyToManyField(to='filtershop_main.company_group')),
            ],
            options={
                'ordering': ['date_creation', 'name'],
                'abstract': False,
            },
            bases=('filtershop_main.entity',),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='videogame_rating',
            old_name='platform',
            new_name='for_platform',
        ),
        migrations.AddField(
            model_name='software',
            name='platforms',
            field=models.ManyToManyField(to='filtershop_main.platform'),
        ),
        migrations.AddField(
            model_name='software',
            name='publishers',
            field=models.ManyToManyField(to='filtershop_main.publisher'),
        ),
        migrations.AddField(
            model_name='software',
            name='studios',
            field=models.ManyToManyField(to='filtershop_main.studio'),
        ),
        migrations.DeleteModel(
            name='TypeOfShop',
        ),
        migrations.AlterField(
            model_name='links_to_shops',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_shop', to='filtershop_main.online_shop'),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
