# Generated by Django 4.2.1 on 2023-05-16 08:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0003_entity_category_filter_profile_typeofentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_category',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='entity_category',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 16, 8, 54, 5, 976522, tzinfo=datetime.timezone.utc), verbose_name='date creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity_category',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='valueforfilter',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='valueforfilter',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valueforfilter',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
