# Generated by Django 4.2.1 on 2023-06-26 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0003_online_shop_remove_shop_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
