# Generated by Django 4.2.1 on 2023-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0004_entity_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='entity_category',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='filter',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='links_to_shops',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='descriptionOfShame',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studio_type',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='typeofentity',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='typeofshop',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='valueforfilter',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='could_be_good_if',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='would_be_good_if',
            field=models.TextField(max_length=1000),
        ),
    ]
