# Generated by Django 4.2.1 on 2023-06-26 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0004_studio_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='known_popularity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='publisher',
            name='spotlight_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='known_popularity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studio',
            name='spotlight_count',
            field=models.IntegerField(default=0),
        ),
    ]
