# Generated by Django 4.2.1 on 2023-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0005_publisher_known_popularity_publisher_spotlight_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_rating',
            name='external_id',
            field=models.TextField(default=123456, help_text='The filter shop can try to prefil the details by fetching the information from one of the shops websites.', max_length=200, verbose_name='External ID (Steam ID, Itch.io URL, Play Store URL, Apple Store URL)'),
            preserve_default=False,
        ),
    ]
