# Generated by Django 4.2.1 on 2023-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0006_videogame_rating_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame_rating',
            name='external_id',
            field=models.CharField(help_text='The filter shop can try to prefil the details by fetching the information from one of the shops websites.', max_length=200, verbose_name='External ID (Steam ID, Itch.io URL, Play Store URL, Apple Store URL)'),
        ),
    ]
