# Generated by Django 4.2.1 on 2023-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0006_alter_entity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='links_to_shops',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(),
        ),
    ]
