# Generated by Django 4.2.1 on 2023-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0007_entity_url_publisher_url_studio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='spotlight_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
