# Generated by Django 4.2.1 on 2023-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0007_alter_videogame_rating_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame_rating',
            name='could_be_good_if',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='gameplay_rating',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='would_be_good_if',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
