# Generated by Django 4.2.1 on 2023-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0008_videogame_common_spotlight_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame_common',
            name='spotlight_count',
            field=models.IntegerField(default=0),
        ),
    ]
