# Generated by Django 4.2.1 on 2023-05-20 12:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0010_alter_entity_entity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='known_popularity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='crapometer',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='general_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hidden_full_cost',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='fully_rotten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='in_hall_of_shame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='money_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='they_have_made_it',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studio',
            name='fully_rotten',
            field=models.BooleanField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studio',
            name='in_hall_of_shame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studio',
            name='money_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studio',
            name='they_have_made_it',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='gameplay_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='ads_supported',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='f2pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='f2play',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='fully_rotten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='good_wo_ads',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='good_wo_iap',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='money_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='videogame_rating',
            name='use_psycho_tech',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images')),
                ('Entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.entity')),
            ],
        ),
    ]
