# Generated by Django 4.2.1 on 2023-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0011_videogame_common_known_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='vignette',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
