# Generated by Django 4.2.1 on 2023-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0012_entity_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='vignette',
            field=models.ImageField(upload_to='images'),
        ),
    ]
