# Generated by Django 4.2.1 on 2023-09-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0014_alter_online_shop_they_have_made_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame_rating',
            name='external_id',
        ),
    ]
