# Generated by Django 4.2.1 on 2023-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0016_new_entry_on_steam_new_entry_on_googleplay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
