# Generated by Django 4.2.1 on 2023-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0017_alter_entity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
