# Generated by Django 4.2.1 on 2023-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0018_alter_publisher_url_alter_studio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='vignette',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
