# Generated by Django 4.2.1 on 2023-09-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0020_alter_links_to_shops_for_entity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='size',
            new_name='size_in_persons',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='size',
            new_name='size_in_persons',
        ),
        migrations.RenameField(
            model_name='studio_type',
            old_name='size',
            new_name='size_in_persons',
        ),
    ]
