# Generated by Django 4.2.1 on 2023-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0021_rename_size_publisher_size_in_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='descriptionOfShame',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
