# Generated by Django 4.2.1 on 2023-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0022_alter_entity_descriptionofshame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related_tags', to='filtershop_main.tag'),
        ),
        migrations.AlterField(
            model_name='online_shop',
            name='group',
            field=models.ManyToManyField(blank=True, to='filtershop_main.company_group'),
        ),
        migrations.AlterField(
            model_name='physical_shop',
            name='group',
            field=models.ManyToManyField(blank=True, to='filtershop_main.company_group'),
        ),
    ]
