# Generated by Django 4.2.1 on 2023-09-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0025_alter_valueforfilter_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfilters',
            name='from_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_filter', to='filtershop_main.filter'),
        ),
        migrations.AlterField(
            model_name='relatedfilters',
            name='to_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_filter', to='filtershop_main.filter'),
        ),
    ]
