# Generated by Django 4.2.1 on 2023-09-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0026_alter_relatedfilters_from_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='in_the_spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
