# Generated by Django 4.2.1 on 2023-09-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0028_videogame_common_in_the_spotlight_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
