# Generated by Django 4.2.1 on 2023-10-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0033_group_alter_alias_created_by_alter_entity_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrelationbetweenfilter',
            name='reverse_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
