# Generated by Django 4.2.1 on 2023-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0037_alter_videogame_common_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='descriptionOfShame',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
