# Generated by Django 4.2.1 on 2023-10-06 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0038_alter_entity_url_alter_sponsor_descriptionofshame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='descriptionOfShame',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='descriptionOfShame',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='they_have_made_it',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='They have made it! (1-> Yes - 2-> Partly thanks to us - 3-> Mostly thanks to us'),
        ),
    ]
