# Generated by Django 4.2.1 on 2023-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0039_publisher_descriptionofshame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofentity',
            name='filters',
            field=models.ManyToManyField(blank=True, to='filtershop_main.filter'),
        ),
    ]
