# Generated by Django 4.2.1 on 2023-10-07 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0041_alter_physical_shop_ethical_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_shop',
            name='size_in_persons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='physical_shop',
            name='size_in_persons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
