# Generated by Django 4.2.1 on 2023-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0042_online_shop_size_in_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curating_fields',
            field=models.ManyToManyField(blank=True, to='filtershop_main.typeofentity'),
        ),
    ]
