# Generated by Django 4.2.1 on 2023-10-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0043_profile_curating_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_category',
            options={'verbose_name': "Video Games' Category", 'verbose_name_plural': "Video Games' Categories"},
        ),
        migrations.RemoveField(
            model_name='online_shop',
            name='shop_logo',
        ),
        migrations.RemoveField(
            model_name='physical_shop',
            name='shop_logo',
        ),
    ]
