# Generated by Django 4.2.1 on 2023-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0044_alter_game_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEndStringFromSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
