# Generated by Django 4.2.1 on 2023-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0045_allendstringfromsteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='size_in_persons',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='size_in_persons',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='type',
        ),
        migrations.AddField(
            model_name='publisher',
            name='size_of_publisher',
            field=models.CharField(choices=[('AR', 'Artisan (5 persons or less)'), ('IN', 'Indie (>5 persons, less than 20)'), ('ME', 'Medium (>20, less than 50)'), ('BI', 'Big (>50 less than 200)'), ('HU', 'Huge (>200)')], default='AR', max_length=2),
        ),
        migrations.AddField(
            model_name='studio',
            name='size_of_studio',
            field=models.CharField(choices=[('AR', 'Artisan (5 persons or less)'), ('IN', 'Indie (>5 persons, less than 20)'), ('ME', 'Medium (>20, less than 50)'), ('BI', 'Big (>50 less than 200)'), ('HU', 'Huge (>200)')], default='AR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Studio_type',
        ),
    ]
