# Generated by Django 4.2.1 on 2023-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0046_remove_publisher_size_in_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_shop',
            name='size_of_shop',
            field=models.CharField(choices=[('AR', 'Artisan (5 persons or less)'), ('IN', 'Indie (>5 persons, less than 20)'), ('ME', 'Medium (>20, less than 50)'), ('BI', 'Big (>50 less than 200)'), ('HU', 'Huge (>200)')], default='AR', max_length=2),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='size_of_shop',
            field=models.CharField(choices=[('AR', 'Artisan (5 persons or less)'), ('IN', 'Indie (>5 persons, less than 20)'), ('ME', 'Medium (>20, less than 50)'), ('BI', 'Big (>50 less than 200)'), ('HU', 'Huge (>200)')], default='AR', max_length=2),
        ),
    ]
