# Generated by Django 4.2.1 on 2023-10-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0050_online_shop_in_the_spotlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='clarity_rating',
        ),
        migrations.RemoveField(
            model_name='software',
            name='do_the_minimum',
        ),
        migrations.RemoveField(
            model_name='software',
            name='heaviness',
        ),
    ]
