# Generated by Django 4.2.1 on 2023-10-12 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0051_remove_software_clarity_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_rating',
            name='crapometer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
