# Generated by Django 4.2.1 on 2023-10-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0052_videogame_rating_crapometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame_rating',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
