# Generated by Django 4.2.1 on 2023-10-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0053_alter_videogame_rating_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_rating',
            name='same_platform_alternative_shop',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='If on the same platform but for a different shop with different conditions (i.e. F2P instead of premium), give the name of the shop'),
        ),
    ]
