# Generated by Django 4.2.1 on 2023-10-13 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0055_alter_videogame_rating_same_platform_alternative_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity_category',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filter',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_category',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studio',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeofentity',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeofrelationbetweenfilter',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videogame_rating',
            name='last_changed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
