# Generated by Django 4.2.1 on 2023-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0056_alias_last_changed_by_entity_last_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_contrib',
            field=models.IntegerField(default=0),
        ),
    ]
