# Generated by Django 4.2.1 on 2023-10-19 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0057_profile_number_of_contrib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='online_shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='physical_shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
        migrations.AlterField(
            model_name='entity',
            name='hidden_full_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Hidden full cost: 0 (none) to 50 (full price again (if not f2p)) to 80 (a lot more) to 100 (infinite, i.e. cannot be won whatever you spend)'),
        ),
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['name'], name='filtershop__name_febe5f_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='filtershop__name_f17d21_idx'),
        ),
        migrations.AddIndex(
            model_name='entity_category',
            index=models.Index(fields=['name'], name='filtershop__name_26a2df_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['name'], name='filtershop__name_118c23_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['name'], name='filtershop__name_74f6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name'], name='filtershop__name_0c49cc_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['name'], name='filtershop__name_0d6f33_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['name'], name='filtershop__name_8ffdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='studio',
            index=models.Index(fields=['name'], name='filtershop__name_b9883d_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='filtershop__name_a152ed_idx'),
        ),
        migrations.AddIndex(
            model_name='typeofentity',
            index=models.Index(fields=['name'], name='filtershop__name_e21526_idx'),
        ),
        migrations.AddIndex(
            model_name='typeofrelationbetweenfilter',
            index=models.Index(fields=['name'], name='filtershop__name_429558_idx'),
        ),
    ]
