# Generated by Django 4.2.1 on 2023-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0058_alter_company_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='description_hidden_full_cost',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='You can give a custom description for the hidden full cost of this product'),
        ),
    ]
