# Generated by Django 4.2.1 on 2024-01-29 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0059_entity_description_hidden_full_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contribution_level',
            field=models.CharField(choices=[('RE', 'Regular user'), ('SU', 'Supporter'), ('SSU', 'Super Supporter')], default='RE', max_length=3),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description_hidden_full_cost',
            field=models.CharField(blank=True, help_text="A default text will be displayed otherwise, from 0 (none) to 100 (infinite: the product cannot be bought fully while it's possible to spend an infinite amoount of money.)", max_length=300, null=True, verbose_name='You can give a custom description for the hidden full cost of this product'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hidden_full_cost',
            field=models.IntegerField(default=0, help_text='0 (none) to 50 (full price again (if not f2p)) to 80 (a lot more) to 100 (infinite, i.e. cannot be won whatever you spend)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Hidden full cost: 0 to 100'),
        ),
    ]
