# Generated by Django 4.2.1 on 2024-01-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0060_profile_contribution_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_Games_By_Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.videogame_common')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.sponsor')),
            ],
        ),
    ]
