# Generated by Django 4.2.1 on 2024-06-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0062_recommended_games_by_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'A Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'A Studio', 'verbose_name_plural': 'Studios'},
        ),
        migrations.RemoveIndex(
            model_name='publisher',
            name='filtershop__name_0d6f33_idx',
        ),
        migrations.RemoveIndex(
            model_name='studio',
            name='filtershop__name_b9883d_idx',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='descriptionOfShame',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='in_hall_of_shame',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='url',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='descriptionOfShame',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='in_hall_of_shame',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='url',
        ),
        migrations.AddField(
            model_name='publisher',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filtershop_main.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filtershop_main.entity'),
            preserve_default=False,
        ),
    ]
