# Generated by Django 4.2 on 2025-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0063_alter_publisher_options_alter_studio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='vignette',
            field=models.ImageField(default='none.jpg', null=True, upload_to='images'),
        ),
    ]
