# Generated by Django 4.2 on 2025-05-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0064_alter_entity_vignette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommended_games_by_contributor',
            old_name='sponsor',
            new_name='contributor',
        ),
    ]
