# Generated by Django 4.2 on 2025-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0065_rename_sponsor_recommended_games_by_contributor_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended_games_by_sponsor',
            name='game',
        ),
        migrations.RemoveField(
            model_name='recommended_games_by_sponsor',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='profile',
            name='recommended_games',
            field=models.ManyToManyField(to='filtershop_main.videogame_common'),
        ),
        migrations.DeleteModel(
            name='Recommended_Games_By_Contributor',
        ),
        migrations.DeleteModel(
            name='Recommended_Games_By_Sponsor',
        ),
    ]
