# Generated by Django 4.2 on 2025-05-24 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0066_remove_recommended_games_by_sponsor_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('review_txt', models.TextField(blank=True, max_length=10000, null=True)),
                ('note', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-5)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related_type', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.videogame_common')),
                ('last_changed_by', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_all_editors', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.profile')),
            ],
            options={
                'ordering': ['date_creation', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommended_Games_By_Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_txt', models.TextField(blank=True, max_length=10000, null=True)),
                ('note', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.videogame_common')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtershop_main.sponsor')),
            ],
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['name'], name='filtershop__name_e170b6_idx'),
        ),
    ]
