# Generated by Django 4.2 on 2025-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0067_reviews_recommended_games_by_sponsor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='filtershop__name_10573b_idx',
            old_name='filtershop__name_e170b6_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contribution_level',
            field=models.CharField(choices=[('RE', 'Regular user'), ('SU', 'Supporter'), ('SSU', 'Super Supporter'), ('CUR', 'Curator')], default='RE', max_length=3),
        ),
    ]
