# Generated by Django 4.2 on 2025-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0068_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='link_sold_from_dev',
            field=models.URLField(blank=True, null=True),
        ),
    ]
