# Generated by Django 4.2 on 2025-12-27 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0069_videogame_common_link_sold_from_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='are_special_bonuses_global',
            field=models.BooleanField(default=False, verbose_name='If global, all shops should give the bonus(es), otherwise only from your direct sales'),
        ),
        migrations.AddField(
            model_name='videogame_common',
            name='special_bonuses',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Given bonuses if someone buy the game'),
        ),
        migrations.AddField(
            model_name='videogame_common',
            name='special_sale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='If you want to apply a special sale only visible here - you will have to apply it yourself. It should not be tracked by an external site as to not hurt future sales'),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='link_sold_from_dev',
            field=models.URLField(blank=True, null=True, verbose_name='Direct link from the developer, if any. Allow to get 100% of the sale.'),
        ),
    ]
