# Generated by Django 4.2 on 2025-12-27 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0070_videogame_common_are_special_bonuses_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame_common',
            name='general_sale',
            field=models.IntegerField(default=0, help_text='If the game is on sale on Steam at least or other external shop', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Percentage off the sale, external shops (mostly Steam)'),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='special_sale',
            field=models.IntegerField(default=0, help_text='If you want to apply a special sale only visible here - you will have to apply it yourself. It should not be tracked by an external site as to not hurt future sales', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Percentage off the sale, directly only'),
        ),
    ]
