# Generated by Django 4.2 on 2026-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0071_videogame_common_general_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForGiveAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.DateField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('has_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SteamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('awarded_to_hash', models.CharField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
