# Generated by Django 4.2 on 2026-02-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0072_emailforgiveaway_steamkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_won', models.DateField(auto_now_add=True)),
                ('steam_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filtershop_main.steamkey')),
            ],
            options={
                'ordering': ['-date_won'],
            },
        ),
    ]
