# Generated by Django 4.2 on 2026-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0073_giveawaywinner'),
    ]

    operations = [
    ]
