# Generated by Django 6.0.3 on 2026-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0074_auto_20260406_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending_approval',
            field=models.BooleanField(default=False, help_text='User needs admin approval to access admin panel'),
        ),
    ]
