# Generated by Django 6.0.3 on 2026-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0075_user_is_pending_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_txt',
            field=models.TextField(blank=True, help_text='You can write a review for this game, which will be visible on the game page.', max_length=10000, null=True, verbose_name='Your review for this game'),
        ),
    ]
