# Generated by Django 6.0.3 on 2026-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0076_alter_review_review_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailforgiveaway',
            name='current_day',
            field=models.DateField(),
        ),
    ]
