# Generated by Django 6.0.3 on 2026-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0077_alter_emailforgiveaway_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_to_shops',
            name='not_a_true_shop',
            field=models.BooleanField(default=False, verbose_name="If the shop is not a true shop (i.e. it's a link to a free drm free copy or something else), check this box so that it will be displayed differently"),
        ),
        migrations.AlterField(
            model_name='giveawaywinner',
            name='date_won',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='videogame_common',
            name='are_special_bonuses_global',
            field=models.BooleanField(default=False, verbose_name='If the bonuses are for all shops (checked) or only from your direct sales'),
        ),
    ]
