# Generated by Django 6.0.3 on 2026-07-12 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0078_links_to_shops_not_a_true_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_on_steam',
            name='videogame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steam_entries', to='filtershop_main.videogame_common'),
        ),
        migrations.AlterField(
            model_name='links_to_shops',
            name='not_a_true_shop',
            field=models.BooleanField(default=False, verbose_name="If the shop is not a true shop (i.e. it's a link to a free drm free copy, a port or something else), check this box so that it will be displayed differently"),
        ),
        migrations.AlterField(
            model_name='tag',
            name='good_or_bad',
            field=models.IntegerField(help_text='1 for good, -1 for bad', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Good or Bad'),
        ),
    ]
