# Generated by Django 6.0.3 on 2026-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0079_entry_on_steam_videogame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_on_steam',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
