# Generated by Django 6.0.3 on 2026-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0080_alter_entry_on_steam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_on_steam',
            name='raw_review_count',
            field=models.IntegerField(default=0),
        ),
    ]
