# Generated by Django 6.0.3 on 2026-07-24 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtershop_main', '0081_entry_on_steam_raw_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(help_text='Three-character code used in /sh/<code>', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Short code must be exactly 3 alphanumeric characters.', regex='^[A-Za-z0-9]{3}$')])),
                ('target_url', models.URLField(verbose_name='Target URL')),
            ],
        ),
    ]
